services:
  - type: web
    name: libretranslate
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /languages
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"